version: '3.7'
services:
  nodejs:
    image: node:12-alpine
    init: true
    depends_on:
      - db
    working_dir: /home/node/app
    volumes:
      - ./app:/home/node/app
      - ./.aws:/root/.aws
    ports:
      - '3000:3000'
    command: /bin/sh -c "npm install && npm run dev"
  db:
    image: mariadb:10.4-bionic
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: xray_example
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db-data:/var/lib/mysql
  xrayd:
    build: ./docker/xrayd
    volumes:
      - ./.aws:/root/.aws
    expose:
      - '2000'
    environment:
      - AWS_REGION=ap-northeast-1
  # awsコマンドを実行するためのコンテナ
  # 常時起動はせずにawsコマンド実行時のみ起動させます
  awscli:
    build: ./docker/awscli
    volumes:
      - ./.aws:/root/.aws
